#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Installs the OpenMRS modules in this directory into the local Maven repo.

set -e
cd  $(dirname $0)

mvn install:install-file -DgroupId=org.openmrs.module -DartifactId=xforms -Dversion=4.3.1 -Dpackaging=jar -Dfile=xforms-4.3.1.jar
mvn install:install-file -DgroupId=org.openmrs.module -DartifactId=xforms-api -Dversion=4.3.1 -Dpackaging=jar -Dfile=xforms-api-4.3.1.jar
